spring.application.name=movie-data-service
spring.data.mongodb.uri=mongodb://localhost:27017/movie_db
server.port=8081

# Elasticsearch configuration
spring.elasticsearch.uris=http://localhost:9200
tmdb.api.key=bea46079b1407d42e9e28af2dd074bcd

